Unit testing2
til2to/todo-list pull request #8
Opened 2023-04-13 17:54 UTC by tomdan-ai

### **In this Project ,The following was implemented:**

- [ ] A test function for editing the task description.
- [ ] A test function for updating an item's 'completed' status.
- [ ] A test for the "Clear all completed" function.
- [ ] Use the mock storage object you have created in Part 1 of this project to mock the localStorage updates.
- [ ] Make sure you group your tests using the describe() method.

2023-04-13 20:04 UTC, BenMukebo requested changes
### Hi @tomdan-ai, @til2to,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Uses mock for functions that used localStorage, DOM or external APIs. ✔️   
- Tests are grouped using the description() method. ✔️   
- The function for editing the task description is tested. ✔️  
- The function for updating an item's 'completed' status is tested. ✔️  
- The "Clear all completed" function is tested. ✔️  
- No linter errors. ✔️    
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 20:04 UTC, BenMukebo commented on editAndClear.test.js
> +// const clearCompleted = require('./src/index.js')
- [ ] Please do not leave unused code as a comment in your codebase. this will make your code much noisier, It is always a good practice to keep your code clean from such comments. 😉 👍🏻

2023-04-13 20:04 UTC, BenMukebo commented on src/modules/drawTask.js
> +    return;
- [ ] Kindly Do not commit `console.log` to your repo. It’s ugly, it kills performance and it can make confidential data visible to anyone using the browser tools to look at your website. Please remove this 🚮

2023-04-14 07:04 UTC, binhussen approved these changes
Hi @tomdan-ai and @BenMukebo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 07:09 UTC, merged